global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'chain-stress-tester'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          environment: 'simulation'